# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/design_tictactoe_PmodGPIO_0_0.xci
# IP: The module: 'design_tictactoe_PmodGPIO_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_pmod_bridge_0_0/PmodGPIO_pmod_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodGPIO_pmod_bridge_0_0 || ORIG_REF_NAME==PmodGPIO_pmod_bridge_0_0}]

# IP: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_axi_gpio_0_0/PmodGPIO_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodGPIO_axi_gpio_0_0 || ORIG_REF_NAME==PmodGPIO_axi_gpio_0_0}]

# IP: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_xlslice_0_0/PmodGPIO_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodGPIO_xlslice_0_0 || ORIG_REF_NAME==PmodGPIO_xlslice_0_0}]

# IP: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_xlslice_0_1/PmodGPIO_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodGPIO_xlslice_0_1 || ORIG_REF_NAME==PmodGPIO_xlslice_0_1}]

# IP: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_xlslice_0_2/PmodGPIO_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodGPIO_xlslice_0_2 || ORIG_REF_NAME==PmodGPIO_xlslice_0_2}]

# IP: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_xlslice_t_0_0/PmodGPIO_xlslice_t_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodGPIO_xlslice_t_0_0 || ORIG_REF_NAME==PmodGPIO_xlslice_t_0_0}]

# IP: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_xlconcat_0_0/PmodGPIO_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodGPIO_xlconcat_0_0 || ORIG_REF_NAME==PmodGPIO_xlconcat_0_0}]

# XDC: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_pmod_bridge_0_0/PmodGPIO_pmod_bridge_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodGPIO_pmod_bridge_0_0 || ORIG_REF_NAME==PmodGPIO_pmod_bridge_0_0}] {/inst }]/inst ]]

# XDC: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_axi_gpio_0_0/PmodGPIO_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodGPIO_axi_gpio_0_0 || ORIG_REF_NAME==PmodGPIO_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_axi_gpio_0_0/PmodGPIO_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_axi_gpio_0_0/PmodGPIO_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodGPIO_axi_gpio_0_0 || ORIG_REF_NAME==PmodGPIO_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/design_tictactoe_PmodGPIO_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_tictactoe_PmodGPIO_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_tictactoe_PmodGPIO_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/design_tictactoe_PmodGPIO_0_0.xci
# IP: The module: 'design_tictactoe_PmodGPIO_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_pmod_bridge_0_0/PmodGPIO_pmod_bridge_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodGPIO_pmod_bridge_0_0 || ORIG_REF_NAME==PmodGPIO_pmod_bridge_0_0}]

# IP: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_axi_gpio_0_0/PmodGPIO_axi_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodGPIO_axi_gpio_0_0 || ORIG_REF_NAME==PmodGPIO_axi_gpio_0_0}]

# IP: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_xlslice_0_0/PmodGPIO_xlslice_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodGPIO_xlslice_0_0 || ORIG_REF_NAME==PmodGPIO_xlslice_0_0}]

# IP: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_xlslice_0_1/PmodGPIO_xlslice_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodGPIO_xlslice_0_1 || ORIG_REF_NAME==PmodGPIO_xlslice_0_1}]

# IP: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_xlslice_0_2/PmodGPIO_xlslice_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodGPIO_xlslice_0_2 || ORIG_REF_NAME==PmodGPIO_xlslice_0_2}]

# IP: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_xlslice_t_0_0/PmodGPIO_xlslice_t_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodGPIO_xlslice_t_0_0 || ORIG_REF_NAME==PmodGPIO_xlslice_t_0_0}]

# IP: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_xlconcat_0_0/PmodGPIO_xlconcat_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodGPIO_xlconcat_0_0 || ORIG_REF_NAME==PmodGPIO_xlconcat_0_0}]

# XDC: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_pmod_bridge_0_0/PmodGPIO_pmod_bridge_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodGPIO_pmod_bridge_0_0 || ORIG_REF_NAME==PmodGPIO_pmod_bridge_0_0}] {/inst }]/inst ]]

# XDC: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_axi_gpio_0_0/PmodGPIO_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodGPIO_axi_gpio_0_0 || ORIG_REF_NAME==PmodGPIO_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_axi_gpio_0_0/PmodGPIO_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_axi_gpio_0_0/PmodGPIO_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodGPIO_axi_gpio_0_0 || ORIG_REF_NAME==PmodGPIO_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/design_tictactoe_PmodGPIO_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_tictactoe_PmodGPIO_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Ardi/Vivado/Project/TicTacToe/TicTacToe.srcs/sources_1/bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/src/PmodGPIO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_tictactoe_PmodGPIO_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
