# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/tictactoe_constrs.xdc

# Block Designs: bd/design_tictactoe/design_tictactoe.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tictactoe || ORIG_REF_NAME==design_tictactoe}]

# IP: bd/design_tictactoe/ip/design_tictactoe_processing_system7_0_0/design_tictactoe_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tictactoe_processing_system7_0_0 || ORIG_REF_NAME==design_tictactoe_processing_system7_0_0}]

# IP: bd/design_tictactoe/ip/design_tictactoe_PmodGPIO_0_0/design_tictactoe_PmodGPIO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tictactoe_PmodGPIO_0_0 || ORIG_REF_NAME==design_tictactoe_PmodGPIO_0_0}]

# IP: bd/design_tictactoe/ip/design_tictactoe_axi_gpio_0_0/design_tictactoe_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tictactoe_axi_gpio_0_0 || ORIG_REF_NAME==design_tictactoe_axi_gpio_0_0}]

# IP: bd/design_tictactoe/ip/design_tictactoe_axi_gpio_0_1/design_tictactoe_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tictactoe_axi_gpio_0_1 || ORIG_REF_NAME==design_tictactoe_axi_gpio_0_1}]

# IP: bd/design_tictactoe/ip/design_tictactoe_axi_gpio_0_2/design_tictactoe_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tictactoe_axi_gpio_0_2 || ORIG_REF_NAME==design_tictactoe_axi_gpio_0_2}]

# IP: bd/design_tictactoe/ip/design_tictactoe_axi_gpio_0_3/design_tictactoe_axi_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tictactoe_axi_gpio_0_3 || ORIG_REF_NAME==design_tictactoe_axi_gpio_0_3}]

# IP: bd/design_tictactoe/ip/design_tictactoe_axi_gpio_0_4/design_tictactoe_axi_gpio_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tictactoe_axi_gpio_0_4 || ORIG_REF_NAME==design_tictactoe_axi_gpio_0_4}]

# IP: bd/design_tictactoe/ip/design_tictactoe_axi_gpio_0_5/design_tictactoe_axi_gpio_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tictactoe_axi_gpio_0_5 || ORIG_REF_NAME==design_tictactoe_axi_gpio_0_5}]

# IP: bd/design_tictactoe/ip/design_tictactoe_axi_gpio_0_6/design_tictactoe_axi_gpio_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tictactoe_axi_gpio_0_6 || ORIG_REF_NAME==design_tictactoe_axi_gpio_0_6}]

# IP: bd/design_tictactoe/ip/design_tictactoe_axi_gpio_0_7/design_tictactoe_axi_gpio_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tictactoe_axi_gpio_0_7 || ORIG_REF_NAME==design_tictactoe_axi_gpio_0_7}]

# IP: bd/design_tictactoe/ip/design_tictactoe_axi_gpio_0_8/design_tictactoe_axi_gpio_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tictactoe_axi_gpio_0_8 || ORIG_REF_NAME==design_tictactoe_axi_gpio_0_8}]

# IP: bd/design_tictactoe/ip/design_tictactoe_ps7_0_axi_periph_0/design_tictactoe_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tictactoe_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_tictactoe_ps7_0_axi_periph_0}]

# IP: bd/design_tictactoe/ip/design_tictactoe_rst_ps7_0_100M_0/design_tictactoe_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tictactoe_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_tictactoe_rst_ps7_0_100M_0}]

# IP: bd/design_tictactoe/ip/design_tictactoe_xbar_0/design_tictactoe_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tictactoe_xbar_0 || ORIG_REF_NAME==design_tictactoe_xbar_0}]

# IP: bd/design_tictactoe/ip/design_tictactoe_axi_gpio_9_0/design_tictactoe_axi_gpio_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tictactoe_axi_gpio_9_0 || ORIG_REF_NAME==design_tictactoe_axi_gpio_9_0}]

# IP: bd/design_tictactoe/ip/design_tictactoe_auto_pc_0/design_tictactoe_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tictactoe_auto_pc_0 || ORIG_REF_NAME==design_tictactoe_auto_pc_0}]

# XDC: bd/design_tictactoe/design_tictactoe_ooc.xdc
